# Generated by Django 5.0 on 2023-12-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_rename_tobeerdo_beer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='image_url',
        ),
    ]
