# Generated by Django 5.0 on 2023-12-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_remove_beer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='beer',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
